### ISSUE TITLE
python setup.py 

### ISSUE THREAD

**Issue by onefool** [cherubicXN/hawp#13]
Hello, sorry to bother you via issue creation.
I would like to ask you about compiling cuda files， python setup.py build_ext --inplace. 
First I compile in cuda11.0 and it fails. Then compile in cuda10.0 to get the _C.***.so file. Then move it to the parsing directory, run the train.py file and still report an error.
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from parsing.detector import WireframeDetector
  File "/home/sun/line/hawp-master/parsing/detector.py", line 4, in <module>
    from parsing.encoder.hafm import HAFMencoder
  File "/home/sun/line/hawp-master/parsing/encoder/__init__.py", line 1, in <module>
    from .hafm import HAFMencoder
  File "/home/sun/line/hawp-master/parsing/encoder/hafm.py", line 4, in <module>
    from parsing import _C
ImportError: cannot import name '_C' from 'parsing' (/home/sun/line/hawp-master/parsing/__init__.py)
Thanks,
Hao Sun

**Comment by cherubicXN** [comment]
Hi Hao Sun,

Sorry to reply to you late. I just saw a new issue that was created 12 days before.

Could you directly compile it with CUDA10.0 in the project directory?

**Comment by onefool** [comment]
> 
> 
> Hi Hao Sun,
> 
> Sorry to reply to you late. I just saw a new issue that was created 12 days before.
> 
> Could you directly compile it with CUDA10.0 in the project directory?

Thanks for your reply. According to your suggestion, I used cuda10.1 to compile directly and it succeeded. thank you very much

**Comment by cherubicXN** [comment]
That's great.
